### ISSUE TITLE
Process for remediation

### ISSUE THREAD

**Issue by dupuy** [dns-violations/dns-violations#22]
Now that people have been "shamed," what is the process for the bashful culprits to report that they have fixed their problem, and what will happen as a result?

Presumably they could submit a PR that moves the DVE markdown file in question into an "archive" or "resolved" subdirectory, adding a new section demonstrating correct behavior, but this should be spelled out in the README.

**Comment by paulehoffman** [comment]
This brings up a very interesting question. This repository has two intertwined purposes that should be decoupled:

- Noting DNS violations seen in the wild that developers might want to be aware of
- Shaming^WTrying to convince operators to fix those violations

The first of these is still important even after the violation has been fixed by the one operator who was identified in the initial ticket. Proposal:

When all operators who exhibit a problem have fixed the problem, change the ticket to indicate that this was seen in the past but not the present. Leave the ticket there in case a different operator (or the same operator...) starts exhibiting the violation again.

**Comment by oerdnj** [comment]
There's a Vendor Response section in the template. I would rather not archive anything as those are usually things that will get repeated over and over by careless implementors.

**Comment by oerdnj** [comment]
But generally I agree that we need to be more explicit. Also the valuable thing here is not the shaming part, but sharing the experience on how to deal with the issues.

**Comment by oerdnj** [comment]
Jerry is setting up a mailing list where we can discuss the process and changes to the process.

**Comment by jelu** [comment]
Archiving DVEs is wrong because even if the reported violator have fixed the issue it can be violated by others, when the reported violator have fixed the issue the DVE should be updated as @oerdnj described.

That said, a DVE may not be per violator, many can make the same mistake and we should not have duplicated DVEs (this will be hard to maintain) for the same problem.

Also since we are adding more machine parse-able formats it can be used by anyone to verify their own implementation, software and/or system. That would not work if we "moved it away".

As we have a Response section, Fixed-date in Metadata and Proposed Fix which can describe correct behavior I consider this issue fixed/closed.
