### ISSUE TITLE
How to use dnstap?

### ISSUE THREAD

**Issue by xnox** [dns-violations/dns-violations#61]
I have a packet capture using Wireshark, is there a way to convert that into dnstap format which seems to be used a lot in other reports?

Should e.g. systemd-resolved be extended to support dnstap too? to e.g. dump the query and/or dump the responses?

Where can I learn more about dnstap?

**Comment by edmonds** [comment]
Hi, Dimitri:

There is a little bit of documentation (mostly slide decks, though) about dnstap at the website, http://dnstap.info/. There is also a very low traffic mailing list at http://lists.redbarn.org/mailman/listinfo/dnstap that should reach most of the people who have implemented dnstap in DNS servers.

dnstap was originally designed as an export format for DNS servers because I was dissatisfied with the complexity of building a fully general importer for DNS packet traffic. While wireshark probably has an IP fragment / TCP segment reassembly engine good enough for DNS pcaps, there is additional DNS protocol context that dnstap makes explicit (e.g. https://github.com/dnstap/dnstap.pb/blob/master/dnstap.proto#L68-L168) which usually has to be inferred, and not always with 100% accuracy. It's also easy to anonymize a dnstap file because the source/destination IP addresses are stored as separate fields that can be omitted, rather than needing to rewrite an IP header.

The dnstap files in this repo were most likely generated by kdig, the tool included with the Knot DNS server. (There is an `identity` field in dnstap payloads that identifies the software that generated the payload, but to read that field you have to already know how to decode dnstap payloads.) Knot has to be built with dnstap support enabled, and then you can use kdig with the -G / -E command-line parameters to read and write dnstap files.

```
       -E tapfile
              Export a dnstap trace of the query and response messages received to the file tapfile.

       -G tapfile
              Generate message output from a previously saved dnstap file tapfile.
```

There are also other tools that can manipulate dnstap files, e.g. recent versions of BIND have a `dnstap-read` utility, and there is a standalone reference decoder, [dnstap-ldns](https://github.com/dnstap/dnstap-ldns).

As to whether systemd-resolved should be extended to support dnstap, maybe, but probably not in the same way that DNS servers have implemented it so far. The big problem has been that traditional DNS servers haven't really had a good way of exporting structured, binary clean log data, so dnstap support has been implemented in those servers by adding external dependencies on [fstrm](https://github.com/farsightsec/fstrm), a library that provides a binary clean message transport over `AF_UNIX` sockets; a protobuf encoder library, usually [protobuf-c](https://github.com/protobuf-c/protobuf-c) for DNS servers written in C, or the official Google protobuf library for DNS servers written in C++; and the [dnstap protobuf message schema](https://github.com/dnstap/dnstap.pb/blob/master/dnstap.proto).

However, the systemd project already has a significant investment and experience with an existing binary clean transport (D-Bus) and serialization format (GVariant), so it may make sense to leverage that infrastructure to export the wire format DNS query/response message payloads (and associated metadata) in a way compatible with dnstap semantics, and then expose that data stream over a D-Bus endpoint. Then external tools could be developed that subscribe to the D-Bus endpoint and convert the data to dnstap format, or otherwise do something useful with the data.

**Comment by vixie** [comment]
is it time to close this issue yet?

**Comment by Habbie** [comment]
There is no action for us here. Closing this issue.
